discord_token: "YOUR DISCORD TOKEN HERE"
statuses:
  - "DISCORD STATUS ROTATOR"
  - "BY WAKURA"
  - "GET NOW > https://github.com/FrolixCZE"

interval: 1 # The interval between changing the status (In seconds)

## MADE BY FROLIX
