discord_token: "YOUR DISCORD TOKEN HERE"
statuses:
  - "DISCORD STATUS ROTATOR"
  - "BY WAKURA"
  - "GET NOW > https://dsc.gg/rezont00ls"

interval: 1 # The interval between changing the status (In seconds)

## MADE BY WAKURA. / FROLIX
## https://dsc.gg/rezont00ls
